name: Development build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet packages
      run: |
        nuget restore ./zstio-tv.sln
      shell: pwsh

    - name: Build WPF App
      run: |
        dotnet build ./zstio-tv.sln --configuration Release
      shell: pwsh

    - name: Publish WPF App
      run: |
        dotnet publish ./zstio-tv.sln --configuration Release --output ./publish
      shell: pwsh

    - name: Rename executable
      run: |
        $artifact = Get-ChildItem -Path ./publish -Recurse -Filter *.exe
        $artifactName = $artifact.Name
        Rename-Item -Path $artifact.FullName -NewName "DEV-ZSTIOTV-$artifactName"
      shell: pwsh

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: wpf-app-artifact
        path: ./publish/DEV-ZSTIOTV-*.exe
